<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AGGameListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        [
            {
            "g_code": "SC07",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SC07",
            "g_code_fun_h5": "SC07",
            "g_code_web": "SC07",
            "g_code_fun_web": "SC07",
            "gameName": {
            "gameName_enus": "Gold Class Deluxe",
            "gameName_zhcn": "豪華金拉霸"
            },
            "imgFileName": "SC07.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH48",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH48",
            "g_code_fun_h5": "WH48",
            "g_code_web": "WH48",
            "g_code_fun_web": "WH48",
            "gameName": {
            "gameName_enus": "Pillar of Fortune",
            "gameName_zhcn": "翻倍寶器"
            },
            "imgFileName": "WH48.png",
            "displaydemo": ""
            },
            {
            "g_code": "TG04",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "TG04",
            "g_code_fun_h5": "TG04",
            "g_code_web": "TG04",
            "g_code_fun_web": "TG04",
            "gameName": {
            "gameName_enus": "Let it ride",
            "gameName_zhcn": "任逍遙"
            },
            "imgFileName": "TG04.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB62",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB62",
            "g_code_fun_h5": "SB62",
            "g_code_web": "SB62",
            "g_code_fun_web": "SB62",
            "gameName": {
            "gameName_enus": "Wild Gods",
            "gameName_zhcn": "狂神對決"
            },
            "imgFileName": "SB62.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB64",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB64",
            "g_code_fun_h5": "SB64",
            "g_code_web": "SB64",
            "g_code_fun_web": "SB64",
            "gameName": {
            "gameName_enus": "Lucky Riches",
            "gameName_zhcn": "財氣沖天"
            },
            "imgFileName": "SB64.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH56",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH56",
            "g_code_fun_h5": "WH56",
            "g_code_web": "WH56",
            "g_code_fun_web": "WH56",
            "gameName": {
            "gameName_enus": "Mermaid Treasure",
            "gameName_zhcn": "美人魚"
            },
            "imgFileName": "WH56.png",
            "displaydemo": ""
            },
            {
            "g_code": "SC06",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SC06",
            "g_code_fun_h5": "SC06",
            "g_code_web": "SC06",
            "g_code_fun_web": "SC06",
            "gameName": {
            "gameName_enus": "Beast Party",
            "gameName_zhcn": "飛禽走獸拉霸"
            },
            "imgFileName": "SC06.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB63",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB63",
            "g_code_fun_h5": "SB63",
            "g_code_web": "SB63",
            "g_code_fun_web": "SB63",
            "gameName": {
            "gameName_enus": "Bingo Slot",
            "gameName_zhcn": "賓果拉霸"
            },
            "imgFileName": "SB63.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB59",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB59",
            "g_code_fun_h5": "SB59",
            "g_code_web": "SB59",
            "g_code_fun_web": "SB59",
            "gameName": {
            "gameName_enus": "Kung Fu All Stars",
            "gameName_zhcn": "功夫傳奇"
            },
            "imgFileName": "SB59.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH52",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH52",
            "g_code_fun_h5": "WH52",
            "g_code_web": "WH52",
            "g_code_fun_web": "WH52",
            "gameName": {
            "gameName_enus": "Bao Zu Po",
            "gameName_zhcn": "包租婆"
            },
            "imgFileName": "WH52.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH62",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH62",
            "g_code_fun_h5": "WH62",
            "g_code_web": "WH62",
            "g_code_fun_web": "WH62",
            "gameName": {
            "gameName_enus": "Sex and Zen",
            "gameName_zhcn": "肉蒲團"
            },
            "imgFileName": "WH62.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB60",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB60",
            "g_code_fun_h5": "SB60",
            "g_code_web": "SB60",
            "g_code_fun_web": "SB60",
            "gameName": {
            "gameName_enus": "Ace Heist",
            "gameName_zhcn": "王牌狂徒"
            },
            "imgFileName": "SB60.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH31",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH31",
            "g_code_fun_h5": "WH31",
            "g_code_web": "WH31",
            "g_code_fun_web": "WH31",
            "gameName": {
            "gameName_enus": "Golden Dragon",
            "gameName_zhcn": "巨龍寶藏"
            },
            "imgFileName": "WH31.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH49",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH49",
            "g_code_fun_h5": "WH49",
            "g_code_web": "WH49",
            "g_code_fun_web": "WH49",
            "gameName": {
            "gameName_enus": "Lucha Heroes",
            "gameName_zhcn": "摔跤英雄"
            },
            "imgFileName": "WH49.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH25",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH25",
            "g_code_fun_h5": "WH25",
            "g_code_web": "WH25",
            "g_code_fun_web": "WH25",
            "gameName": {
            "gameName_enus": "The Nutcracker",
            "gameName_zhcn": "胡桃夾子"
            },
            "imgFileName": "WH25.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH65",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH65",
            "g_code_fun_h5": "WH65",
            "g_code_web": "WH65",
            "g_code_fun_web": "WH65",
            "gameName": {
            "gameName_enus": "Temple Raider",
            "gameName_zhcn": "神廟麗影"
            },
            "imgFileName": "WH65.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB56",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB56",
            "g_code_fun_h5": "SB56",
            "g_code_web": "SB56",
            "g_code_fun_web": "SB56",
            "gameName": {
            "gameName_enus": "Vegas Vegas",
            "gameName_zhcn": "賭城之夜"
            },
            "imgFileName": "SB56.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH54",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH54",
            "g_code_fun_h5": "WH54",
            "g_code_web": "WH54",
            "g_code_fun_web": "WH54",
            "gameName": {
            "gameName_enus": "Ultra Shift",
            "gameName_zhcn": "極品飆車"
            },
            "imgFileName": "WH54.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH26",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH26",
            "g_code_fun_h5": "WH26",
            "g_code_web": "WH26",
            "g_code_fun_web": "WH26",
            "gameName": {
            "gameName_enus": "Sushi Nights",
            "gameName_zhcn": "壽司大食客"
            },
            "imgFileName": "WH26.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH40",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH40",
            "g_code_fun_h5": "WH40",
            "g_code_web": "WH40",
            "g_code_fun_web": "WH40",
            "gameName": {
            "gameName_enus": "Peking Opera",
            "gameName_zhcn": "皇家戲台"
            },
            "imgFileName": "WH40.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH44",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH44",
            "g_code_fun_h5": "WH44",
            "g_code_web": "WH44",
            "g_code_fun_web": "WH44",
            "gameName": {
            "gameName_enus": "Steampunk War",
            "gameName_zhcn": "蒸汽戰爭"
            },
            "imgFileName": "WH44.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB58",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB58",
            "g_code_fun_h5": "SB58",
            "g_code_web": "SB58",
            "g_code_fun_web": "SB58",
            "gameName": {
            "gameName_enus": "Sexy Succubus",
            "gameName_zhcn": "魅惑魔女"
            },
            "imgFileName": "SB58.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH36",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH36",
            "g_code_fun_h5": "WH36",
            "g_code_web": "WH36",
            "g_code_fun_web": "WH36",
            "gameName": {
            "gameName_enus": "One Percenter",
            "gameName_zhcn": "橫行霸道"
            },
            "imgFileName": "WH36.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH42",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH42",
            "g_code_fun_h5": "WH42",
            "g_code_web": "WH42",
            "g_code_fun_web": "WH42",
            "gameName": {
            "gameName_enus": "Young and Dangerous",
            "gameName_zhcn": "古惑仔"
            },
            "imgFileName": "WH42.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH55",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH55",
            "g_code_fun_h5": "WH55",
            "g_code_web": "WH55",
            "g_code_fun_web": "WH55",
            "gameName": {
            "gameName_enus": "Money Monster",
            "gameName_zhcn": "神奇寵物"
            },
            "imgFileName": "WH55.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB57",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB57",
            "g_code_fun_h5": "SB57",
            "g_code_web": "SB57",
            "g_code_fun_web": "SB57",
            "gameName": {
            "gameName_enus": "Evil Dragons",
            "gameName_zhcn": "魔龍"
            },
            "imgFileName": "SB57.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH19",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH19",
            "g_code_fun_h5": "WH19",
            "g_code_web": "WH19",
            "g_code_fun_web": "WH19",
            "gameName": {
            "gameName_enus": "Treasure Tarot",
            "gameName_zhcn": "財寶塔羅"
            },
            "imgFileName": "WH19.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH28",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH28",
            "g_code_fun_h5": "WH28",
            "g_code_web": "WH28",
            "g_code_fun_web": "WH28",
            "gameName": {
            "gameName_enus": "Egyptian Treasure",
            "gameName_zhcn": "埃及寶藏"
            },
            "imgFileName": "WH28.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH27",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH27",
            "g_code_fun_h5": "WH27",
            "g_code_web": "WH27",
            "g_code_fun_web": "WH27",
            "gameName": {
            "gameName_enus": "Kabuki Gold",
            "gameName_zhcn": "和風劇院"
            },
            "imgFileName": "WH27.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH30",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH30",
            "g_code_fun_h5": "WH30",
            "g_code_web": "WH30",
            "g_code_fun_web": "WH30",
            "gameName": {
            "gameName_enus": "Fortune Alchemy",
            "gameName_zhcn": "點石成金"
            },
            "imgFileName": "WH30.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH23",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH23",
            "g_code_fun_h5": "WH23",
            "g_code_web": "WH23",
            "g_code_fun_web": "WH23",
            "gameName": {
            "gameName_enus": "Fengshen Yanyi",
            "gameName_zhcn": "封神演義"
            },
            "imgFileName": "WH23.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH07",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH07",
            "g_code_fun_h5": "WH07",
            "g_code_web": "WH07",
            "g_code_fun_web": "WH07",
            "gameName": {
            "gameName_enus": "Festival Lions",
            "gameName_zhcn": "五獅進寶"
            },
            "imgFileName": "WH07.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH02",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH02",
            "g_code_fun_h5": "WH02",
            "g_code_web": "WH02",
            "g_code_fun_web": "WH02",
            "gameName": {
            "gameName_enus": "Joan of Arc",
            "gameName_zhcn": "聖女貞德"
            },
            "imgFileName": "WH02.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH12",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH12",
            "g_code_fun_h5": "WH12",
            "g_code_web": "WH12",
            "g_code_fun_web": "WH12",
            "gameName": {
            "gameName_enus": "Panda's Gold",
            "gameName_zhcn": "發財熊貓"
            },
            "imgFileName": "WH12.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH35",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH35",
            "g_code_fun_h5": "WH35",
            "g_code_web": "WH35",
            "g_code_fun_web": "WH35",
            "gameName": {
            "gameName_enus": "Koi Treasure",
            "gameName_zhcn": "招財錦鯉"
            },
            "imgFileName": "WH35.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH38",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH38",
            "g_code_fun_h5": "WH38",
            "g_code_web": "WH38",
            "g_code_fun_web": "WH38",
            "gameName": {
            "gameName_enus": "Chinese Zodiac",
            "gameName_zhcn": "十二生肖"
            },
            "imgFileName": "WH38.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH20",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH20",
            "g_code_fun_h5": "WH20",
            "g_code_web": "WH20",
            "g_code_fun_web": "WH20",
            "gameName": {
            "gameName_enus": "Huluwa",
            "gameName_zhcn": "葫蘆兄弟"
            },
            "imgFileName": "WH20.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH32",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH32",
            "g_code_fun_h5": "WH32",
            "g_code_web": "WH32",
            "g_code_fun_web": "WH32",
            "gameName": {
            "gameName_enus": "TanWanLanYue",
            "gameName_zhcn": "貪玩藍月"
            },
            "imgFileName": "WH32.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH34",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH34",
            "g_code_fun_h5": "WH34",
            "g_code_web": "WH34",
            "g_code_fun_web": "WH34",
            "gameName": {
            "gameName_enus": "Touchdown Hottie",
            "gameName_zhcn": "內衣橄欖球"
            },
            "imgFileName": "WH34.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH18",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH18",
            "g_code_fun_h5": "WH18",
            "g_code_web": "WH18",
            "g_code_fun_web": "WH18",
            "gameName": {
            "gameName_enus": "Snow White",
            "gameName_zhcn": "白雪公主"
            },
            "imgFileName": "WH18.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB55",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB55",
            "g_code_fun_h5": "SB55",
            "g_code_web": "SB55",
            "g_code_fun_web": "SB55",
            "gameName": {
            "gameName_enus": "Lucky Combo",
            "gameName_zhcn": "多寶魚蝦蟹"
            },
            "imgFileName": "SB55.png",
            "displaydemo": ""
            },
            {
            "g_code": "WC01",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WC01",
            "g_code_fun_h5": "WC01",
            "g_code_web": "WC01",
            "g_code_fun_web": "WC01",
            "gameName": {
            "gameName_enus": "Happy Jump",
            "gameName_zhcn": "跳跳樂"
            },
            "imgFileName": "WC01.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH24",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH24",
            "g_code_fun_h5": "WH24",
            "g_code_web": "WH24",
            "g_code_fun_web": "WH24",
            "gameName": {
            "gameName_enus": "The Living Dead",
            "gameName_zhcn": "殭屍來襲"
            },
            "imgFileName": "WH24.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH21",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH21",
            "g_code_fun_h5": "WH21",
            "g_code_web": "WH21",
            "g_code_fun_web": "WH21",
            "gameName": {
            "gameName_enus": "Bloody Kisses",
            "gameName_zhcn": "永恆之吻"
            },
            "imgFileName": "WH21.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH29",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH29",
            "g_code_fun_h5": "WH29",
            "g_code_web": "WH29",
            "g_code_fun_web": "WH29",
            "gameName": {
            "gameName_enus": "Witch's Quest",
            "gameName_zhcn": "狂野女巫"
            },
            "imgFileName": "WH29.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH22",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH22",
            "g_code_fun_h5": "WH22",
            "g_code_web": "WH22",
            "g_code_fun_web": "WH22",
            "gameName": {
            "gameName_enus": "Dark Joker",
            "gameName_zhcn": "恐怖嘉年華"
            },
            "imgFileName": "WH22.png",
            "displaydemo": ""
            },
            {
            "g_code": "SC05",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SC05",
            "g_code_fun_h5": "SC05",
            "g_code_web": "SC05",
            "g_code_fun_web": "SC05",
            "gameName": {
            "gameName_enus": "Wild 777",
            "gameName_zhcn": "百搭777"
            },
            "imgFileName": "SC05.png",
            "displaydemo": ""
            },
            {
            "g_code": "WA01",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WA01",
            "g_code_fun_h5": "WA01",
            "g_code_web": "WA01",
            "g_code_fun_web": "WA01",
            "gameName": {
            "gameName_enus": "Diamond Queen",
            "gameName_zhcn": "鑽石女王"
            },
            "imgFileName": "WA01.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH17",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH17",
            "g_code_fun_h5": "WH17",
            "g_code_web": "WH17",
            "g_code_fun_web": "WH17",
            "gameName": {
            "gameName_enus": "The Moon Lady",
            "gameName_zhcn": "嫦娥奔月"
            },
            "imgFileName": "WH17.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH10",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH10",
            "g_code_fun_h5": "WH10",
            "g_code_web": "WH10",
            "g_code_fun_web": "WH10",
            "gameName": {
            "gameName_enus": "Alice's Adventures",
            "gameName_zhcn": "愛麗絲大冒險"
            },
            "imgFileName": "WH10.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH11",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH11",
            "g_code_fun_h5": "WH11",
            "g_code_web": "WH11",
            "g_code_fun_web": "WH11",
            "gameName": {
            "gameName_enus": "The Storm",
            "gameName_zhcn": "戰火風雲"
            },
            "imgFileName": "WH11.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH06",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH06",
            "g_code_fun_h5": "WH06",
            "g_code_web": "WH06",
            "g_code_fun_web": "WH06",
            "gameName": {
            "gameName_enus": "King Arthur",
            "gameName_zhcn": "亞瑟王"
            },
            "imgFileName": "WH06.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH04",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH04",
            "g_code_fun_h5": "WH04",
            "g_code_web": "WH04",
            "g_code_fun_web": "WH04",
            "gameName": {
            "gameName_enus": "Mucha Goddesses",
            "gameName_zhcn": "穆夏女神"
            },
            "imgFileName": "WH04.png",
            "displaydemo": ""
            },
            {
            "g_code": "EP02",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "EP02",
            "g_code_fun_h5": "EP02",
            "g_code_web": "EP02",
            "g_code_fun_web": "EP02",
            "gameName": {
            "gameName_enus": "DragonTiger",
            "gameName_zhcn": "龍虎"
            },
            "imgFileName": "EP02.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH03",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH03",
            "g_code_fun_h5": "WH03",
            "g_code_web": "WH03",
            "g_code_fun_web": "WH03",
            "gameName": {
            "gameName_enus": "Real Champions",
            "gameName_zhcn": "冠軍足球"
            },
            "imgFileName": "WH03.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB51",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB51",
            "g_code_fun_h5": "SB51",
            "g_code_web": "SB51",
            "g_code_fun_web": "SB51",
            "gameName": {
            "gameName_enus": "King of Glory",
            "gameName_zhcn": "王者傳說"
            },
            "imgFileName": "SB51.png",
            "displaydemo": ""
            },
            {
            "g_code": "EP03",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "EP03",
            "g_code_fun_h5": "EP03",
            "g_code_web": "EP03",
            "g_code_fun_web": "EP03",
            "gameName": {
            "gameName_enus": "Sicbo",
            "gameName_zhcn": "骰寶"
            },
            "imgFileName": "EP03.png",
            "displaydemo": ""
            },
            {
            "g_code": "WH01",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "WH01",
            "g_code_fun_h5": "WH01",
            "g_code_web": "WH01",
            "g_code_fun_web": "WH01",
            "gameName": {
            "gameName_enus": "Alibaba",
            "gameName_zhcn": "阿里巴巴"
            },
            "imgFileName": "WH01.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB47",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB47",
            "g_code_fun_h5": "SB47",
            "g_code_web": "SB47",
            "g_code_fun_web": "SB47",
            "gameName": {
            "gameName_enus": "Mystic Gems",
            "gameName_zhcn": "神奇寶石"
            },
            "imgFileName": "SB47.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB50",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB50",
            "g_code_fun_h5": "SB50",
            "g_code_web": "SB50",
            "g_code_fun_web": "SB50",
            "gameName": {
            "gameName_enus": "Mr XIN",
            "gameName_zhcn": "XIN哥來了"
            },
            "imgFileName": "SB50.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB49",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB49",
            "g_code_fun_h5": "SB49",
            "g_code_web": "SB49",
            "g_code_fun_web": "SB49",
            "gameName": {
            "gameName_enus": "The Dragon Pearl Gold",
            "gameName_zhcn": "金龍珠"
            },
            "imgFileName": "SB49.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB45",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB45",
            "g_code_fun_h5": "SB45",
            "g_code_web": "SB45",
            "g_code_fun_web": "SB45",
            "gameName": {
            "gameName_enus": "Legend of the Dragon",
            "gameName_zhcn": "猛龍傳奇"
            },
            "imgFileName": "SB45.png",
            "displaydemo": ""
            },
            {
            "g_code": "SC03",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SC03",
            "g_code_fun_h5": "SC03",
            "g_code_web": "SC03",
            "g_code_fun_web": "SC03",
            "gameName": {
            "gameName_enus": "Gold Class",
            "gameName_zhcn": "金拉霸"
            },
            "imgFileName": "SC03.png",
            "displaydemo": ""
            },
            {
            "g_code": "SX02",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SX02",
            "g_code_fun_h5": "SX02",
            "g_code_web": "SX02",
            "g_code_fun_web": "SX02",
            "gameName": {
            "gameName_enus": "Street Battle",
            "gameName_zhcn": "街頭烈戰"
            },
            "imgFileName": "SX02.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB34",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB34",
            "g_code_fun_h5": "SB34",
            "g_code_web": "SB34",
            "g_code_fun_web": "SB34",
            "gameName": {
            "gameName_enus": "Ice Crush",
            "gameName_zhcn": "冰河世界"
            },
            "imgFileName": "SB34.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB33",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB33",
            "g_code_fun_h5": "SB33",
            "g_code_web": "SB33",
            "g_code_fun_web": "SB33",
            "gameName": {
            "gameName_enus": "Candy Quest",
            "gameName_zhcn": "糖果碰碰樂"
            },
            "imgFileName": "SB33.png",
            "displaydemo": ""
            },
            {
            "g_code": "FRU2",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "FRU2",
            "g_code_fun_h5": "FRU2",
            "g_code_web": "FRU2",
            "g_code_fun_web": "FRU2",
            "gameName": {
            "gameName_enus": "Fruit Slot 2",
            "gameName_zhcn": "水果拉霸2"
            },
            "imgFileName": "FRU2.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB37",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB37",
            "g_code_fun_h5": "SB37",
            "g_code_web": "SB37",
            "g_code_fun_web": "SB37",
            "gameName": {
            "gameName_enus": "Shanghai Bund",
            "gameName_zhcn": "上海百樂門"
            },
            "imgFileName": "SB37.png",
            "displaydemo": ""
            },
            {
            "g_code": "PKBD",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "PKBD",
            "g_code_fun_h5": "PKBD",
            "g_code_web": "PKBD",
            "g_code_fun_web": "PKBD",
            "gameName": {
            "gameName_enus": "Deuces Wild",
            "gameName_zhcn": "百搭二王"
            },
            "imgFileName": "PKBD.png",
            "displaydemo": ""
            },
            {
            "g_code": "PKBB",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "PKBB",
            "g_code_fun_h5": "PKBB",
            "g_code_web": "PKBB",
            "g_code_fun_web": "PKBB",
            "gameName": {
            "gameName_enus": "Bonus Deuces Wild",
            "gameName_zhcn": "紅利百搭"
            },
            "imgFileName": "PKBB.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB30",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB30",
            "g_code_fun_h5": "SB30",
            "g_code_web": "SB30",
            "g_code_fun_web": "SB30",
            "gameName": {
            "gameName_enus": "Year of the Monkey",
            "gameName_zhcn": "靈猴獻瑞"
            },
            "imgFileName": "SB30.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB28",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB28",
            "g_code_fun_h5": "SB28",
            "g_code_web": "SB28",
            "g_code_fun_web": "SB28",
            "gameName": {
            "gameName_enus": "God of Wu Fortune",
            "gameName_zhcn": "武財神"
            },
            "imgFileName": "SB28.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB07",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB07",
            "g_code_fun_h5": "SB07",
            "g_code_web": "SB07",
            "g_code_fun_web": "SB07",
            "gameName": {
            "gameName_enus": "Chinese Chess Slot",
            "gameName_zhcn": "象棋老虎機"
            },
            "imgFileName": "SB07.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB09",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB09",
            "g_code_fun_h5": "SB09",
            "g_code_web": "SB09",
            "g_code_fun_web": "SB09",
            "gameName": {
            "gameName_enus": "Chess Slot",
            "gameName_zhcn": "西洋棋老虎機"
            },
            "imgFileName": "SB09.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB10",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB10",
            "g_code_fun_h5": "SB10",
            "g_code_web": "SB10",
            "g_code_fun_web": "SB10",
            "gameName": {
            "gameName_enus": "Happy Farm",
            "gameName_zhcn": "開心農場"
            },
            "imgFileName": "SB10.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB08",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB08",
            "g_code_fun_h5": "SB08",
            "g_code_web": "SB08",
            "g_code_fun_web": "SB08",
            "gameName": {
            "gameName_enus": "Mahjong Slot",
            "gameName_zhcn": "麻將老虎機"
            },
            "imgFileName": "SB08.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB11",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB11",
            "g_code_fun_h5": "SB11",
            "g_code_web": "SB11",
            "g_code_fun_web": "SB11",
            "gameName": {
            "gameName_enus": "Summer Campsite",
            "gameName_zhcn": "夏日營地"
            },
            "imgFileName": "SB11.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB01",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB01",
            "g_code_fun_h5": "SB01",
            "g_code_web": "SB01",
            "g_code_fun_web": "SB01",
            "gameName": {
            "gameName_enus": "Space Odyssey",
            "gameName_zhcn": "太空漫遊"
            },
            "imgFileName": "SB01.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB06",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB06",
            "g_code_fun_h5": "SB06",
            "g_code_web": "SB06",
            "g_code_fun_web": "SB06",
            "gameName": {
            "gameName_enus": "Samurai",
            "gameName_zhcn": "日本武士"
            },
            "imgFileName": "SB06.png",
            "displaydemo": ""
            },
            {
            "g_code": "SB02",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "SB02",
            "g_code_fun_h5": "SB02",
            "g_code_web": "SB02",
            "g_code_fun_web": "SB02",
            "gameName": {
            "gameName_enus": "Garden Vintage",
            "gameName_zhcn": "復古花園"
            },
            "imgFileName": "SB02.png",
            "displaydemo": ""
            },
            {
            "g_code": "PKBJ",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "PKBJ",
            "g_code_fun_h5": "PKBJ",
            "g_code_web": "PKBJ",
            "g_code_fun_web": "PKBJ",
            "gameName": {
            "gameName_enus": "Video poker2 (jacks or better)",
            "gameName_zhcn": "傑克高手(大版視頻撲克)"
            },
            "imgFileName": "PKBJ.png",
            "displaydemo": ""
            },
            {
            "g_code": "FRU",
            "g_type": "SLOT",
            "p_code": "AG",
            "p_type": "SL",
            "h5": "1",
            "web": "1",
            "h5_fun": "-1",
            "web_fun": "-1",
            "status": "1",
            "g_progressive": "-1",
            "g_code_h5": "FRU",
            "g_code_fun_h5": "FRU",
            "g_code_web": "FRU",
            "g_code_fun_web": "FRU",
            "gameName": {
            "gameName_enus": "Fruit Slot",
            "gameName_zhcn": "水果拉霸"
            },
            "imgFileName": "FRU.png",
            "displaydemo": ""
            }
            ]
    }
}
