<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AGGameListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
   {
        [
           [
            "game_id"=> "SC07",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Gold Class Deluxe",
            "image"=> "SC07.png",

           ],
           [
            "game_id"=> "WH48",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH48",
            "game_id_fun_h5"=> "WH48",
            "game_id_web"=> "WH48",
            "game_id_fun_web"=> "WH48",
            "name_en"=>[
            "name_en_enus"=> "Pillar of Fortune",
            "name_en_zhcn"=> "翻倍寶器"
           ],
            "image"=> "WH48.png",

           ],
           [
            "game_id"=> "TG04",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "TG04",
            "game_id_fun_h5"=> "TG04",
            "game_id_web"=> "TG04",
            "game_id_fun_web"=> "TG04",
            "name_en"=>[
            "name_en_enus"=> "Let it ride",
            "name_en_zhcn"=> "任逍遙"
           ],
            "image"=> "TG04.png",

           ],
           [
            "game_id"=> "SB62",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB62",
            "game_id_fun_h5"=> "SB62",
            "game_id_web"=> "SB62",
            "game_id_fun_web"=> "SB62",
            "name_en"=>[
            "name_en_enus"=> "Wild Gods",
            "name_en_zhcn"=> "狂神對決"
           ],
            "image"=> "SB62.png",

           ],
           [
            "game_id"=> "SB64",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB64",
            "game_id_fun_h5"=> "SB64",
            "game_id_web"=> "SB64",
            "game_id_fun_web"=> "SB64",
            "name_en"=>[
            "name_en_enus"=> "Lucky Riches",
            "name_en_zhcn"=> "財氣沖天"
           ],
            "image"=> "SB64.png",

           ],
           [
            "game_id"=> "WH56",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH56",
            "game_id_fun_h5"=> "WH56",
            "game_id_web"=> "WH56",
            "game_id_fun_web"=> "WH56",
            "name_en"=>[
            "name_en_enus"=> "Mermaid Treasure",
            "name_en_zhcn"=> "美人魚"
           ],
            "image"=> "WH56.png",

           ],
           [
            "game_id"=> "SC06",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SC06",
            "game_id_fun_h5"=> "SC06",
            "game_id_web"=> "SC06",
            "game_id_fun_web"=> "SC06",
            "name_en"=>[
            "name_en_enus"=> "Beast Party",
            "name_en_zhcn"=> "飛禽走獸拉霸"
           ],
            "image"=> "SC06.png",

           ],
           [
            "game_id"=> "SB63",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB63",
            "game_id_fun_h5"=> "SB63",
            "game_id_web"=> "SB63",
            "game_id_fun_web"=> "SB63",
            "name_en"=>[
            "name_en_enus"=> "Bingo Slot",
            "name_en_zhcn"=> "賓果拉霸"
           ],
            "image"=> "SB63.png",

           ],
           [
            "game_id"=> "SB59",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB59",
            "game_id_fun_h5"=> "SB59",
            "game_id_web"=> "SB59",
            "game_id_fun_web"=> "SB59",
            "name_en"=>[
            "name_en_enus"=> "Kung Fu All Stars",
            "name_en_zhcn"=> "功夫傳奇"
           ],
            "image"=> "SB59.png",

           ],
           [
            "game_id"=> "WH52",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH52",
            "game_id_fun_h5"=> "WH52",
            "game_id_web"=> "WH52",
            "game_id_fun_web"=> "WH52",
            "name_en"=>[
            "name_en_enus"=> "Bao Zu Po",
            "name_en_zhcn"=> "包租婆"
           ],
            "image"=> "WH52.png",

           ],
           [
            "game_id"=> "WH62",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH62",
            "game_id_fun_h5"=> "WH62",
            "game_id_web"=> "WH62",
            "game_id_fun_web"=> "WH62",
            "name_en"=>[
            "name_en_enus"=> "Sex and Zen",
            "name_en_zhcn"=> "肉蒲團"
           ],
            "image"=> "WH62.png",

           ],
           [
            "game_id"=> "SB60",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB60",
            "game_id_fun_h5"=> "SB60",
            "game_id_web"=> "SB60",
            "game_id_fun_web"=> "SB60",
            "name_en"=>[
            "name_en_enus"=> "Ace Heist",
            "name_en_zhcn"=> "王牌狂徒"
           ],
            "image"=> "SB60.png",

           ],
           [
            "game_id"=> "WH31",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH31",
            "game_id_fun_h5"=> "WH31",
            "game_id_web"=> "WH31",
            "game_id_fun_web"=> "WH31",
            "name_en"=>[
            "name_en_enus"=> "Golden Dragon",
            "name_en_zhcn"=> "巨龍寶藏"
           ],
            "image"=> "WH31.png",

           ],
           [
            "game_id"=> "WH49",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH49",
            "game_id_fun_h5"=> "WH49",
            "game_id_web"=> "WH49",
            "game_id_fun_web"=> "WH49",
            "name_en"=>[
            "name_en_enus"=> "Lucha Heroes",
            "name_en_zhcn"=> "摔跤英雄"
           ],
            "image"=> "WH49.png",

           ],
           [
            "game_id"=> "WH25",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH25",
            "game_id_fun_h5"=> "WH25",
            "game_id_web"=> "WH25",
            "game_id_fun_web"=> "WH25",
            "name_en"=>[
            "name_en_enus"=> "The Nutcracker",
            "name_en_zhcn"=> "胡桃夾子"
           ],
            "image"=> "WH25.png",

           ],
           [
            "game_id"=> "WH65",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH65",
            "game_id_fun_h5"=> "WH65",
            "game_id_web"=> "WH65",
            "game_id_fun_web"=> "WH65",
            "name_en"=>[
            "name_en_enus"=> "Temple Raider",
            "name_en_zhcn"=> "神廟麗影"
           ],
            "image"=> "WH65.png",

           ],
           [
            "game_id"=> "SB56",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB56",
            "game_id_fun_h5"=> "SB56",
            "game_id_web"=> "SB56",
            "game_id_fun_web"=> "SB56",
            "name_en"=>[
            "name_en_enus"=> "Vegas Vegas",
            "name_en_zhcn"=> "賭城之夜"
           ],
            "image"=> "SB56.png",

           ],
           [
            "game_id"=> "WH54",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH54",
            "game_id_fun_h5"=> "WH54",
            "game_id_web"=> "WH54",
            "game_id_fun_web"=> "WH54",
            "name_en"=>[
            "name_en_enus"=> "Ultra Shift",
            "name_en_zhcn"=> "極品飆車"
           ],
            "image"=> "WH54.png",

           ],
           [
            "game_id"=> "WH26",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH26",
            "game_id_fun_h5"=> "WH26",
            "game_id_web"=> "WH26",
            "game_id_fun_web"=> "WH26",
            "name_en"=>[
            "name_en_enus"=> "Sushi Nights",
            "name_en_zhcn"=> "壽司大食客"
           ],
            "image"=> "WH26.png",

           ],
           [
            "game_id"=> "WH40",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH40",
            "game_id_fun_h5"=> "WH40",
            "game_id_web"=> "WH40",
            "game_id_fun_web"=> "WH40",
            "name_en"=>[
            "name_en_enus"=> "Peking Opera",
            "name_en_zhcn"=> "皇家戲台"
           ],
            "image"=> "WH40.png",

           ],
           [
            "game_id"=> "WH44",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH44",
            "game_id_fun_h5"=> "WH44",
            "game_id_web"=> "WH44",
            "game_id_fun_web"=> "WH44",
            "name_en"=>[
            "name_en_enus"=> "Steampunk War",
            "name_en_zhcn"=> "蒸汽戰爭"
           ],
            "image"=> "WH44.png",

           ],
           [
            "game_id"=> "SB58",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB58",
            "game_id_fun_h5"=> "SB58",
            "game_id_web"=> "SB58",
            "game_id_fun_web"=> "SB58",
            "name_en"=>[
            "name_en_enus"=> "Sexy Succubus",
            "name_en_zhcn"=> "魅惑魔女"
           ],
            "image"=> "SB58.png",

           ],
           [
            "game_id"=> "WH36",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH36",
            "game_id_fun_h5"=> "WH36",
            "game_id_web"=> "WH36",
            "game_id_fun_web"=> "WH36",
            "name_en"=>[
            "name_en_enus"=> "One Percenter",
            "name_en_zhcn"=> "橫行霸道"
           ],
            "image"=> "WH36.png",

           ],
           [
            "game_id"=> "WH42",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH42",
            "game_id_fun_h5"=> "WH42",
            "game_id_web"=> "WH42",
            "game_id_fun_web"=> "WH42",
            "name_en"=>[
            "name_en_enus"=> "Young and Dangerous",
            "name_en_zhcn"=> "古惑仔"
           ],
            "image"=> "WH42.png",

           ],
           [
            "game_id"=> "WH55",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH55",
            "game_id_fun_h5"=> "WH55",
            "game_id_web"=> "WH55",
            "game_id_fun_web"=> "WH55",
            "name_en"=>[
            "name_en_enus"=> "Money Monster",
            "name_en_zhcn"=> "神奇寵物"
           ],
            "image"=> "WH55.png",

           ],
           [
            "game_id"=> "SB57",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB57",
            "game_id_fun_h5"=> "SB57",
            "game_id_web"=> "SB57",
            "game_id_fun_web"=> "SB57",
            "name_en"=>[
            "name_en_enus"=> "Evil Dragons",
            "name_en_zhcn"=> "魔龍"
           ],
            "image"=> "SB57.png",

           ],
           [
            "game_id"=> "WH19",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH19",
            "game_id_fun_h5"=> "WH19",
            "game_id_web"=> "WH19",
            "game_id_fun_web"=> "WH19",
            "name_en"=>[
            "name_en_enus"=> "Treasure Tarot",
            "name_en_zhcn"=> "財寶塔羅"
           ],
            "image"=> "WH19.png",

           ],
           [
            "game_id"=> "WH28",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH28",
            "game_id_fun_h5"=> "WH28",
            "game_id_web"=> "WH28",
            "game_id_fun_web"=> "WH28",
            "name_en"=>[
            "name_en_enus"=> "Egyptian Treasure",
            "name_en_zhcn"=> "埃及寶藏"
           ],
            "image"=> "WH28.png",

           ],
           [
            "game_id"=> "WH27",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH27",
            "game_id_fun_h5"=> "WH27",
            "game_id_web"=> "WH27",
            "game_id_fun_web"=> "WH27",
            "name_en"=>[
            "name_en_enus"=> "Kabuki Gold",
            "name_en_zhcn"=> "和風劇院"
           ],
            "image"=> "WH27.png",

           ],
           [
            "game_id"=> "WH30",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH30",
            "game_id_fun_h5"=> "WH30",
            "game_id_web"=> "WH30",
            "game_id_fun_web"=> "WH30",
            "name_en"=>[
            "name_en_enus"=> "Fortune Alchemy",
            "name_en_zhcn"=> "點石成金"
           ],
            "image"=> "WH30.png",

           ],
           [
            "game_id"=> "WH23",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH23",
            "game_id_fun_h5"=> "WH23",
            "game_id_web"=> "WH23",
            "game_id_fun_web"=> "WH23",
            "name_en"=>[
            "name_en_enus"=> "Fengshen Yanyi",
            "name_en_zhcn"=> "封神演義"
           ],
            "image"=> "WH23.png",

           ],
           [
            "game_id"=> "WH07",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH07",
            "game_id_fun_h5"=> "WH07",
            "game_id_web"=> "WH07",
            "game_id_fun_web"=> "WH07",
            "name_en"=>[
            "name_en_enus"=> "Festival Lions",
            "name_en_zhcn"=> "五獅進寶"
           ],
            "image"=> "WH07.png",

           ],
           [
            "game_id"=> "WH02",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH02",
            "game_id_fun_h5"=> "WH02",
            "game_id_web"=> "WH02",
            "game_id_fun_web"=> "WH02",
            "name_en"=>[
            "name_en_enus"=> "Joan of Arc",
            "name_en_zhcn"=> "聖女貞德"
           ],
            "image"=> "WH02.png",

           ],
           [
            "game_id"=> "WH12",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH12",
            "game_id_fun_h5"=> "WH12",
            "game_id_web"=> "WH12",
            "game_id_fun_web"=> "WH12",
            "name_en"=>[
            "name_en_enus"=> "Panda's Gold",
            "name_en_zhcn"=> "發財熊貓"
           ],
            "image"=> "WH12.png",

           ],
           [
            "game_id"=> "WH35",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH35",
            "game_id_fun_h5"=> "WH35",
            "game_id_web"=> "WH35",
            "game_id_fun_web"=> "WH35",
            "name_en"=>[
            "name_en_enus"=> "Koi Treasure",
            "name_en_zhcn"=> "招財錦鯉"
           ],
            "image"=> "WH35.png",

           ],
           [
            "game_id"=> "WH38",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH38",
            "game_id_fun_h5"=> "WH38",
            "game_id_web"=> "WH38",
            "game_id_fun_web"=> "WH38",
            "name_en"=>[
            "name_en_enus"=> "Chinese Zodiac",
            "name_en_zhcn"=> "十二生肖"
           ],
            "image"=> "WH38.png",

           ],
           [
            "game_id"=> "WH20",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH20",
            "game_id_fun_h5"=> "WH20",
            "game_id_web"=> "WH20",
            "game_id_fun_web"=> "WH20",
            "name_en"=>[
            "name_en_enus"=> "Huluwa",
            "name_en_zhcn"=> "葫蘆兄弟"
           ],
            "image"=> "WH20.png",

           ],
           [
            "game_id"=> "WH32",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH32",
            "game_id_fun_h5"=> "WH32",
            "game_id_web"=> "WH32",
            "game_id_fun_web"=> "WH32",
            "name_en"=>[
            "name_en_enus"=> "TanWanLanYue",
            "name_en_zhcn"=> "貪玩藍月"
           ],
            "image"=> "WH32.png",

           ],
           [
            "game_id"=> "WH34",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH34",
            "game_id_fun_h5"=> "WH34",
            "game_id_web"=> "WH34",
            "game_id_fun_web"=> "WH34",
            "name_en"=>[
            "name_en_enus"=> "Touchdown Hottie",
            "name_en_zhcn"=> "內衣橄欖球"
           ],
            "image"=> "WH34.png",

           ],
           [
            "game_id"=> "WH18",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH18",
            "game_id_fun_h5"=> "WH18",
            "game_id_web"=> "WH18",
            "game_id_fun_web"=> "WH18",
            "name_en"=>[
            "name_en_enus"=> "Snow White",
            "name_en_zhcn"=> "白雪公主"
           ],
            "image"=> "WH18.png",

           ],
           [
            "game_id"=> "SB55",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB55",
            "game_id_fun_h5"=> "SB55",
            "game_id_web"=> "SB55",
            "game_id_fun_web"=> "SB55",
            "name_en"=>[
            "name_en_enus"=> "Lucky Combo",
            "name_en_zhcn"=> "多寶魚蝦蟹"
           ],
            "image"=> "SB55.png",

           ],
           [
            "game_id"=> "WC01",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WC01",
            "game_id_fun_h5"=> "WC01",
            "game_id_web"=> "WC01",
            "game_id_fun_web"=> "WC01",
            "name_en"=>[
            "name_en_enus"=> "Happy Jump",
            "name_en_zhcn"=> "跳跳樂"
           ],
            "image"=> "WC01.png",

           ],
           [
            "game_id"=> "WH24",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH24",
            "game_id_fun_h5"=> "WH24",
            "game_id_web"=> "WH24",
            "game_id_fun_web"=> "WH24",
            "name_en"=>[
            "name_en_enus"=> "The Living Dead",
            "name_en_zhcn"=> "殭屍來襲"
           ],
            "image"=> "WH24.png",

           ],
           [
            "game_id"=> "WH21",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH21",
            "game_id_fun_h5"=> "WH21",
            "game_id_web"=> "WH21",
            "game_id_fun_web"=> "WH21",
            "name_en"=>[
            "name_en_enus"=> "Bloody Kisses",
            "name_en_zhcn"=> "永恆之吻"
           ],
            "image"=> "WH21.png",

           ],
           [
            "game_id"=> "WH29",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH29",
            "game_id_fun_h5"=> "WH29",
            "game_id_web"=> "WH29",
            "game_id_fun_web"=> "WH29",
            "name_en"=>[
            "name_en_enus"=> "Witch's Quest",
            "name_en_zhcn"=> "狂野女巫"
           ],
            "image"=> "WH29.png",

           ],
           [
            "game_id"=> "WH22",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH22",
            "game_id_fun_h5"=> "WH22",
            "game_id_web"=> "WH22",
            "game_id_fun_web"=> "WH22",
            "name_en"=>[
            "name_en_enus"=> "Dark Joker",
            "name_en_zhcn"=> "恐怖嘉年華"
           ],
            "image"=> "WH22.png",

           ],
           [
            "game_id"=> "SC05",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SC05",
            "game_id_fun_h5"=> "SC05",
            "game_id_web"=> "SC05",
            "game_id_fun_web"=> "SC05",
            "name_en"=>[
            "name_en_enus"=> "Wild 777",
            "name_en_zhcn"=> "百搭777"
           ],
            "image"=> "SC05.png",

           ],
           [
            "game_id"=> "WA01",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WA01",
            "game_id_fun_h5"=> "WA01",
            "game_id_web"=> "WA01",
            "game_id_fun_web"=> "WA01",
            "name_en"=>[
            "name_en_enus"=> "Diamond Queen",
            "name_en_zhcn"=> "鑽石女王"
           ],
            "image"=> "WA01.png",

           ],
           [
            "game_id"=> "WH17",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH17",
            "game_id_fun_h5"=> "WH17",
            "game_id_web"=> "WH17",
            "game_id_fun_web"=> "WH17",
            "name_en"=>[
            "name_en_enus"=> "The Moon Lady",
            "name_en_zhcn"=> "嫦娥奔月"
           ],
            "image"=> "WH17.png",

           ],
           [
            "game_id"=> "WH10",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH10",
            "game_id_fun_h5"=> "WH10",
            "game_id_web"=> "WH10",
            "game_id_fun_web"=> "WH10",
            "name_en"=>[
            "name_en_enus"=> "Alice's Adventures",
            "name_en_zhcn"=> "愛麗絲大冒險"
           ],
            "image"=> "WH10.png",

           ],
           [
            "game_id"=> "WH11",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH11",
            "game_id_fun_h5"=> "WH11",
            "game_id_web"=> "WH11",
            "game_id_fun_web"=> "WH11",
            "name_en"=>[
            "name_en_enus"=> "The Storm",
            "name_en_zhcn"=> "戰火風雲"
           ],
            "image"=> "WH11.png",

           ],
           [
            "game_id"=> "WH06",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH06",
            "game_id_fun_h5"=> "WH06",
            "game_id_web"=> "WH06",
            "game_id_fun_web"=> "WH06",
            "name_en"=>[
            "name_en_enus"=> "King Arthur",
            "name_en_zhcn"=> "亞瑟王"
           ],
            "image"=> "WH06.png",

           ],
           [
            "game_id"=> "WH04",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH04",
            "game_id_fun_h5"=> "WH04",
            "game_id_web"=> "WH04",
            "game_id_fun_web"=> "WH04",
            "name_en"=>[
            "name_en_enus"=> "Mucha Goddesses",
            "name_en_zhcn"=> "穆夏女神"
           ],
            "image"=> "WH04.png",

           ],
           [
            "game_id"=> "EP02",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "EP02",
            "game_id_fun_h5"=> "EP02",
            "game_id_web"=> "EP02",
            "game_id_fun_web"=> "EP02",
            "name_en"=>[
            "name_en_enus"=> "DragonTiger",
            "name_en_zhcn"=> "龍虎"
           ],
            "image"=> "EP02.png",

           ],
           [
            "game_id"=> "WH03",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH03",
            "game_id_fun_h5"=> "WH03",
            "game_id_web"=> "WH03",
            "game_id_fun_web"=> "WH03",
            "name_en"=>[
            "name_en_enus"=> "Real Champions",
            "name_en_zhcn"=> "冠軍足球"
           ],
            "image"=> "WH03.png",

           ],
           [
            "game_id"=> "SB51",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB51",
            "game_id_fun_h5"=> "SB51",
            "game_id_web"=> "SB51",
            "game_id_fun_web"=> "SB51",
            "name_en"=>[
            "name_en_enus"=> "King of Glory",
            "name_en_zhcn"=> "王者傳說"
           ],
            "image"=> "SB51.png",

           ],
           [
            "game_id"=> "EP03",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "EP03",
            "game_id_fun_h5"=> "EP03",
            "game_id_web"=> "EP03",
            "game_id_fun_web"=> "EP03",
            "name_en"=>[
            "name_en_enus"=> "Sicbo",
            "name_en_zhcn"=> "骰寶"
           ],
            "image"=> "EP03.png",

           ],
           [
            "game_id"=> "WH01",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "WH01",
            "game_id_fun_h5"=> "WH01",
            "game_id_web"=> "WH01",
            "game_id_fun_web"=> "WH01",
            "name_en"=>[
            "name_en_enus"=> "Alibaba",
            "name_en_zhcn"=> "阿里巴巴"
           ],
            "image"=> "WH01.png",

           ],
           [
            "game_id"=> "SB47",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB47",
            "game_id_fun_h5"=> "SB47",
            "game_id_web"=> "SB47",
            "game_id_fun_web"=> "SB47",
            "name_en"=>[
            "name_en_enus"=> "Mystic Gems",
            "name_en_zhcn"=> "神奇寶石"
           ],
            "image"=> "SB47.png",

           ],
           [
            "game_id"=> "SB50",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB50",
            "game_id_fun_h5"=> "SB50",
            "game_id_web"=> "SB50",
            "game_id_fun_web"=> "SB50",
            "name_en"=>[
            "name_en_enus"=> "Mr XIN",
            "name_en_zhcn"=> "XIN哥來了"
           ],
            "image"=> "SB50.png",

           ],
           [
            "game_id"=> "SB49",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB49",
            "game_id_fun_h5"=> "SB49",
            "game_id_web"=> "SB49",
            "game_id_fun_web"=> "SB49",
            "name_en"=>[
            "name_en_enus"=> "The Dragon Pearl Gold",
            "name_en_zhcn"=> "金龍珠"
           ],
            "image"=> "SB49.png",

           ],
           [
            "game_id"=> "SB45",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB45",
            "game_id_fun_h5"=> "SB45",
            "game_id_web"=> "SB45",
            "game_id_fun_web"=> "SB45",
            "name_en"=>[
            "name_en_enus"=> "Legend of the Dragon",
            "name_en_zhcn"=> "猛龍傳奇"
           ],
            "image"=> "SB45.png",

           ],
           [
            "game_id"=> "SC03",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SC03",
            "game_id_fun_h5"=> "SC03",
            "game_id_web"=> "SC03",
            "game_id_fun_web"=> "SC03",
            "name_en"=>[
            "name_en_enus"=> "Gold Class",
            "name_en_zhcn"=> "金拉霸"
           ],
            "image"=> "SC03.png",

           ],
           [
            "game_id"=> "SX02",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SX02",
            "game_id_fun_h5"=> "SX02",
            "game_id_web"=> "SX02",
            "game_id_fun_web"=> "SX02",
            "name_en"=>[
            "name_en_enus"=> "Street Battle",
            "name_en_zhcn"=> "街頭烈戰"
           ],
            "image"=> "SX02.png",

           ],
           [
            "game_id"=> "SB34",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB34",
            "game_id_fun_h5"=> "SB34",
            "game_id_web"=> "SB34",
            "game_id_fun_web"=> "SB34",
            "name_en"=>[
            "name_en_enus"=> "Ice Crush",
            "name_en_zhcn"=> "冰河世界"
           ],
            "image"=> "SB34.png",

           ],
           [
            "game_id"=> "SB33",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB33",
            "game_id_fun_h5"=> "SB33",
            "game_id_web"=> "SB33",
            "game_id_fun_web"=> "SB33",
            "name_en"=>[
            "name_en_enus"=> "Candy Quest",
            "name_en_zhcn"=> "糖果碰碰樂"
           ],
            "image"=> "SB33.png",

           ],
           [
            "game_id"=> "FRU2",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "FRU2",
            "game_id_fun_h5"=> "FRU2",
            "game_id_web"=> "FRU2",
            "game_id_fun_web"=> "FRU2",
            "name_en"=>[
            "name_en_enus"=> "Fruit Slot 2",
            "name_en_zhcn"=> "水果拉霸2"
           ],
            "image"=> "FRU2.png",

           ],
           [
            "game_id"=> "SB37",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB37",
            "game_id_fun_h5"=> "SB37",
            "game_id_web"=> "SB37",
            "game_id_fun_web"=> "SB37",
            "name_en"=>[
            "name_en_enus"=> "Shanghai Bund",
            "name_en_zhcn"=> "上海百樂門"
           ],
            "image"=> "SB37.png",

           ],
           [
            "game_id"=> "PKBD",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "PKBD",
            "game_id_fun_h5"=> "PKBD",
            "game_id_web"=> "PKBD",
            "game_id_fun_web"=> "PKBD",
            "name_en"=>[
            "name_en_enus"=> "Deuces Wild",
            "name_en_zhcn"=> "百搭二王"
           ],
            "image"=> "PKBD.png",

           ],
           [
            "game_id"=> "PKBB",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "PKBB",
            "game_id_fun_h5"=> "PKBB",
            "game_id_web"=> "PKBB",
            "game_id_fun_web"=> "PKBB",
            "name_en"=>[
            "name_en_enus"=> "Bonus Deuces Wild",
            "name_en_zhcn"=> "紅利百搭"
           ],
            "image"=> "PKBB.png",

           ],
           [
            "game_id"=> "SB30",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB30",
            "game_id_fun_h5"=> "SB30",
            "game_id_web"=> "SB30",
            "game_id_fun_web"=> "SB30",
            "name_en"=>[
            "name_en_enus"=> "Year of the Monkey",
            "name_en_zhcn"=> "靈猴獻瑞"
           ],
            "image"=> "SB30.png",

           ],
           [
            "game_id"=> "SB28",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB28",
            "game_id_fun_h5"=> "SB28",
            "game_id_web"=> "SB28",
            "game_id_fun_web"=> "SB28",
            "name_en"=>[
            "name_en_enus"=> "God of Wu Fortune",
            "name_en_zhcn"=> "武財神"
           ],
            "image"=> "SB28.png",

           ],
           [
            "game_id"=> "SB07",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB07",
            "game_id_fun_h5"=> "SB07",
            "game_id_web"=> "SB07",
            "game_id_fun_web"=> "SB07",
            "name_en"=>[
            "name_en_enus"=> "Chinese Chess Slot",
            "name_en_zhcn"=> "象棋老虎機"
           ],
            "image"=> "SB07.png",

           ],
           [
            "game_id"=> "SB09",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB09",
            "game_id_fun_h5"=> "SB09",
            "game_id_web"=> "SB09",
            "game_id_fun_web"=> "SB09",
            "name_en"=>[
            "name_en_enus"=> "Chess Slot",
            "name_en_zhcn"=> "西洋棋老虎機"
           ],
            "image"=> "SB09.png",

           ],
           [
            "game_id"=> "SB10",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB10",
            "game_id_fun_h5"=> "SB10",
            "game_id_web"=> "SB10",
            "game_id_fun_web"=> "SB10",
            "name_en"=>[
            "name_en_enus"=> "Happy Farm",
            "name_en_zhcn"=> "開心農場"
           ],
            "image"=> "SB10.png",

           ],
           [
            "game_id"=> "SB08",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB08",
            "game_id_fun_h5"=> "SB08",
            "game_id_web"=> "SB08",
            "game_id_fun_web"=> "SB08",
            "name_en"=>[
            "name_en_enus"=> "Mahjong Slot",
            "name_en_zhcn"=> "麻將老虎機"
           ],
            "image"=> "SB08.png",

           ],
           [
            "game_id"=> "SB11",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB11",
            "game_id_fun_h5"=> "SB11",
            "game_id_web"=> "SB11",
            "game_id_fun_web"=> "SB11",
            "name_en"=>[
            "name_en_enus"=> "Summer Campsite",
            "name_en_zhcn"=> "夏日營地"
           ],
            "image"=> "SB11.png",

           ],
           [
            "game_id"=> "SB01",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB01",
            "game_id_fun_h5"=> "SB01",
            "game_id_web"=> "SB01",
            "game_id_fun_web"=> "SB01",
            "name_en"=>[
            "name_en_enus"=> "Space Odyssey",
            "name_en_zhcn"=> "太空漫遊"
           ],
            "image"=> "SB01.png",

           ],
           [
            "game_id"=> "SB06",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB06",
            "game_id_fun_h5"=> "SB06",
            "game_id_web"=> "SB06",
            "game_id_fun_web"=> "SB06",
            "name_en"=>[
            "name_en_enus"=> "Samurai",
            "name_en_zhcn"=> "日本武士"
           ],
            "image"=> "SB06.png",

           ],
           [
            "game_id"=> "SB02",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "SB02",
            "game_id_fun_h5"=> "SB02",
            "game_id_web"=> "SB02",
            "game_id_fun_web"=> "SB02",
            "name_en"=>[
            "name_en_enus"=> "Garden Vintage",
            "name_en_zhcn"=> "復古花園"
           ],
            "image"=> "SB02.png",

           ],
           [
            "game_id"=> "PKBJ",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "PKBJ",
            "game_id_fun_h5"=> "PKBJ",
            "game_id_web"=> "PKBJ",
            "game_id_fun_web"=> "PKBJ",
            "name_en"=>[
            "name_en_enus"=> "Video poker2 (jacks or better)",
            "name_en_zhcn"=> "傑克高手(大版視頻撲克)"
           ],
            "image"=> "PKBJ.png",

           ],
           [
            "game_id"=> "FRU",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            "h5"=> "1",
            "web"=> "1",
            "h5_fun"=> "-1",
            "web_fun"=> "-1",
            "status"=> "1",
            "g_progressive"=> "-1",
            "game_id_h5"=> "FRU",
            "game_id_fun_h5"=> "FRU",
            "game_id_web"=> "FRU",
            "game_id_fun_web"=> "FRU",
            "name_en"=>[
            "name_en_enus"=> "Fruit Slot",
            "name_en_zhcn"=> "水果拉霸"
           ],
            "image"=> "FRU.png",

           ]
            ]
   ]
}
