<?php

namespace Database\Seeders;

use App\Models\Admin\GameList;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AGGameListSeeder extends Seeder
{
   public function run(): void
   {
      $data = [
           [
            "game_id"=> "SC07",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Gold Class Deluxe",
            "image"=> "SC07.png",
           ],
           [
            "game_id"=> "WH48",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Pillar of Fortune",
            "image"=> "WH48.png",
           ],
           [
            "game_id"=> "TG04",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Let it ride",
            "image"=> "TG04.png",
           ],
           [
            "game_id"=> "SB62",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Wild Gods",
            "image"=> "SB62.png",
           ],
           [
            "game_id"=> "SB64",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Lucky Riches",
            "image"=> "SB64.png",
           ],
           [
            "game_id"=> "WH56",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Mermaid Treasure",
            "image"=> "WH56.png",
           ],
           [
            "game_id"=> "SC06",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Beast Party",
            "image"=> "SC06.png",

           ],
           [
            "game_id"=> "SB63",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Bingo Slot",
            "image"=> "SB63.png",
           ],
           [
            "game_id"=> "SB59",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Kung Fu All Stars",
            "image"=> "SB59.png",
           ],
           [
            "game_id"=> "WH52",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Bao Zu Po",
            "image"=> "WH52.png",
           ],
           [
            "game_id"=> "WH62",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Sex and Zen",
            "image"=> "WH62.png",
           ],
           [
            "game_id"=> "SB60",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Ace Heist",
            "image"=> "SB60.png",
           ],
           [
            "game_id"=> "WH31",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Golden Dragon",
            "image"=> "WH31.png",
           ],
           [
            "game_id"=> "WH49",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Lucha Heroes",
            "image"=> "WH49.png",
           ],
           [
            "game_id"=> "WH25",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "The Nutcracker",
            "image"=> "WH25.png",
           ],
           [
            "game_id"=> "WH65",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Temple Raider",
            "image"=> "WH65.png",
           ],
           [
            "game_id"=> "SB56",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Vegas Vegas",
            "image"=> "SB56.png",
           ],
           [
            "game_id"=> "WH54",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Ultra Shift",
            "image"=> "WH54.png",
           ],
           [
            "game_id"=> "WH26",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Sushi Nights",
            "image"=> "WH26.png",
           ],
           [
            "game_id"=> "WH40",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Peking Opera",
            "image"=> "WH40.png",
           ],
           [
            "game_id"=> "WH44",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Steampunk War",
            "image"=> "WH44.png",
           ],
           [
            "game_id"=> "SB58",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Sexy Succubus",
            "image"=> "SB58.png",
           ],
           [
            "game_id"=> "WH36",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "One Percenter",
            "image"=> "WH36.png",
           ],
           [
            "game_id"=> "WH42",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Young and Dangerous",
            "image"=> "WH42.png",
           ],
           [
            "game_id"=> "WH55",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Money Monster",
            "image"=> "WH55.png",
           ],
           [
            "game_id"=> "SB57",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Evil Dragons",
            "image"=> "SB57.png",
           ],
           [
            "game_id"=> "WH19",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Treasure Tarot",
            "image"=> "WH19.png",
           ],
           [
            "game_id"=> "WH28",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Egyptian Treasure",
            "image"=> "WH28.png",
           ],
           [
            "game_id"=> "WH27",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Kabuki Gold",
            "image"=> "WH27.png",
           ],
           [
            "game_id"=> "WH30",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Fortune Alchemy",
            "image"=> "WH30.png",
           ],
           [
            "game_id"=> "WH23",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Fengshen Yanyi",
            "image"=> "WH23.png",
           ],
           [
            "game_id"=> "WH07",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Festival Lions",
            "image"=> "WH07.png",
           ],
           [
            "game_id"=> "WH02",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Joan of Arc",
            "image"=> "WH02.png",
           ],
           [
            "game_id"=> "WH12",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Panda's Gold",
            "image"=> "WH12.png",
           ],
           [
            "game_id"=> "WH35",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Koi Treasure",
            "image"=> "WH35.png",
           ],
           [
            "game_id"=> "WH38",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Chinese Zodiac",
            "image"=> "WH38.png",
           ],
           [
            "game_id"=> "WH20",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Huluwa",
            "image"=> "WH20.png",
           ],
           [
            "game_id"=> "WH32",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "TanWanLanYue",
            "image"=> "WH32.png",
           ],
           [
            "game_id"=> "WH34",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Touchdown Hottie",
            "image"=> "WH34.png",
           ],
           [
            "game_id"=> "WH18",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Snow White",
            "image"=> "WH18.png",
           ],
           [
            "game_id"=> "SB55",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Lucky Combo",
            "image"=> "SB55.png",
           ],
           [
            "game_id"=> "WC01",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Happy Jump",
            "image"=> "WC01.png",
           ],
           [
            "game_id"=> "WH24",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "The Living Dead",
            "image"=> "WH24.png",
           ],
           [
            "game_id"=> "WH21",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Bloody Kisses",
            "image"=> "WH21.png",
           ],
           [
            "game_id"=> "WH29",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=>  "Witch's Quest",
            "image"=> "WH29.png",
           ],
           [
            "game_id"=> "WH22",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Dark Joker",
            "image"=> "WH22.png",
           ],
           [
            "game_id"=> "SC05",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Wild 777",
            "image"=> "SC05.png",
           ],
           [
            "game_id"=> "WA01",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Diamond Queen",
            "image"=> "WA01.png",
           ],
           [
            "game_id"=> "WH17",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "The Moon Lady",
            "image"=> "WH17.png",
           ],
           [
            "game_id"=> "WH10",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Alice's Adventures",
            "image"=> "WH10.png",
           ],
           [
            "game_id"=> "WH11",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "The Storm",
            "image"=> "WH11.png",
           ],
           [
            "game_id"=> "WH06",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "King Arthur",
            "image"=> "WH06.png",
           ],
           [
            "game_id"=> "WH04",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Mucha Goddesses",
            "image"=> "WH04.png",
           ],
           [
            "game_id"=> "EP02",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "DragonTiger",
            "image"=> "EP02.png",
           ],
           [
            "game_id"=> "WH03",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Real Champions",
            "image"=> "WH03.png",
           ],
           [
            "game_id"=> "SB51",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "King of Glory",
            "image"=> "SB51.png",
           ],
           [
            "game_id"=> "EP03",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Sicbo",
            "image"=> "EP03.png",
           ],
           [
            "game_id"=> "WH01",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Alibaba",
            "image"=> "WH01.png",
           ],
           [
            "game_id"=> "SB47",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Mystic Gems",
            "image"=> "SB47.png",
           ],
           [
            "game_id"=> "SB50",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Mr XIN",
            "image"=> "SB50.png",
           ],
           [
            "game_id"=> "SB49",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "The Dragon Pearl Gold",
            "image"=> "SB49.png",
           ],
           [
            "game_id"=> "SB45",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Legend of the Dragon",
            "image"=> "SB45.png",
           ],
           [
            "game_id"=> "SC03",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Gold Class",
            "image"=> "SC03.png",
           ],
           [
            "game_id"=> "SX02",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Street Battle",
            "image"=> "SX02.png",
           ],
           [
            "game_id"=> "SB34",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Ice Crush",
            "image"=> "SB34.png",
           ],
           [
            "game_id"=> "SB33",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Candy Quest",
            "image"=> "SB33.png",
           ],
           [
            "game_id"=> "FRU2",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Fruit Slot 2",
            "image"=> "FRU2.png",
           ],
           [
            "game_id"=> "SB37",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Shanghai Bund",
            "image"=> "SB37.png",
           ],
           [
            "game_id"=> "PKBD",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Deuces Wild",
            "image"=> "PKBD.png",
           ],
           [
            "game_id"=> "PKBB",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Bonus Deuces Wild",
            "image"=> "PKBB.png",
           ],
           [
            "game_id"=> "SB30",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Year of the Monkey",
            "image"=> "SB30.png",
           ],
           [
            "game_id"=> "SB28",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "God of Wu Fortune",
            "image"=> "SB28.png",
           ],
           [
            "game_id"=> "SB07",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en" => "Chinese Chess Slot",
            "image"=> "SB07.png",
           ],
           [
            "game_id"=> "SB09",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Chess Slot",
            "image"=> "SB09.png",
           ],
           [
            "game_id"=> "SB10",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Happy Farm",
            "image"=> "SB10.png",
           ],
           [
            "game_id"=> "SB08",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Mahjong Slot",
            "image"=> "SB08.png",
           ],
           [
            "game_id"=> "SB11",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Summer Campsite",
            "image"=> "SB11.png",
           ],
           [
            "game_id"=> "SB01",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Space Odyssey",
            "image"=> "SB01.png",
           ],
           [
            "game_id"=> "SB06",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Samurai",
            "image"=> "SB06.png",
           ],
           [
            "game_id"=> "SB02",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en"=> "Garden Vintage",
            "image"=> "SB02.png",
           ],
           [
            "game_id"=> "PKBJ",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en" => "Video poker2 (jacks or better)",
            "image"=> "PKBJ.png",
           ],
           [
            "game_id"=> "FRU",
            "g_type"=> "SLOT",
            "p_code"=> "AG",
            "p_type"=> "SL",
            'provider_id' => 1,
            'game_type_id' =>10,
            "name_en" => "Fruit Slot",
            "image"=> "FRU.png",
           ]
         ];
         foreach($data as $value)
         {

            GameList::create([
                'game_id' => $value['game_id'],
                'provider_id' => $value['provider_id'],
                'game_type_id' => $value['game_type_id'],
                'name_en' => $value['name_en'],
                'image' => $value['image']
            ]);
         }
   } 
}